### ISSUE TITLE
Video Tour

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mosaic_grid#2]
I am hoping to create video tours of some Backdrop CMS modules. I started with this one, because it's a fresh and new module for Backdrop. 

https://www.youtube.com/watch?v=UO5cnsMXBs0

Let me know if you see any mistakes or have suggestions, I may take a second stab at it.

**Comment by korontari** [comment]
Hello Tim! Thank you for making the video - this was quite unexpected and very pleasing to see it! :) 
I don't see any mistakes regarding the process shown on the video except for some issues with the module itself. And I must say that seeing how other people use the module helps to find the flaws and get ideas on how to improve it.  So here are a few comments I have:
1. You mentioned in the video that you had problems with spinner styles. Could you provide a bit more info on that? I will try to check it out. Feel free to post a new issue for this module.
2. I have also experienced that at times the grid fails to build correctly. I don't  think this is related to image size. I have tested it with relatively large images and they worked fine. I noticed that it somehow depends on the chosen layout and the default Boxton layout in particular. I will explore this more and try to figure out if I can do anything with it.
3. When configuring image field in views, the 'Formatter' dropdown is where you can assign a lightbox if you have it installed. For instance this can be a Featherlight or Photoswipe that are available for Backdrop.
4. I have a general idea regarding learning videos for the Backdrop. I think it would be great to put them in one place (youtube channel or directly on backdropcms.org etc.) and have an easily noticeable link from Backdrop site's front page. So that new visitors could quickly find something that would get them familiar with the cms.

**Comment by korontari** [comment]
Oh, I have just noticed a closed issue regarding loading spinners. Please disregard my first question. :)

**Comment by korontari** [comment]
I'm closing the issue as the video refers to a very old version that is largely outdated.

**Comment by stpaultim** [comment]
@korontari Should I unpublish the video?

I will at least at a comment saying that the module has changed quite a bit. I've not looked at your module in a while. I would love to create a new updated video, but i'm not sure how likely that is.

**Comment by korontari** [comment]
Hi @stpaultim! First of all, thank you very much for making the video - Backdrop does need more explanation videos.
I think it makes sense to at least state that the module has changed considerably. The style settings are now different and it uses a more stable jQuery plugin to build the grid. Of course I would very much appreciate if you can make another video with the latest version, but I understand it needs time. 🙏
